// Hebrew labels for the admin dashboard UI.
// Keys mirror Zod schema field names; values are what the editor sees.

export const LABELS = {
  show: {
    _entity: 'הצגה / סדנא',
    _entityPlural: 'הצגות וסדנאות',
    id: 'מזהה (ID)',
    slug: 'כתובת URL ידידותית (אופציונלי)',
    title: 'שם ההצגה / סדנא',
    category: 'קהל יעד',
    priority: 'חשיבות תצוגה',
    kind: 'סוג',
    kindOptions: {
      show: 'הצגה רגילה',
      workshop: 'סדנא (כוללת הצגות בתוכה)',
    },
    containedShowIds: 'הצגות הכלולות בסדנא',
    mainImg: 'תמונה ראשית',
    presentationFormats: 'גרסאות של ההצגה (למשל: תיאטרון בובות, הצגת יחיד)',
    presentationFormatsItem: {
      image: 'תמונת הגרסה',
      caption: 'תיאור הגרסה',
    },
    gallery: 'גלריית תמונות',
    description: 'תיאור ההצגה',
    audience: 'קהל היעד (טקסט חופשי)',
    creatorName: 'שם היוצרת',
    creatorIntro: 'מילות פתיחה על היוצרת',
    creatorCredentials: 'רקע מקצועי',
    socialProof: 'היכן ההצגה הוצגה',
    phone: 'טלפון ליצירת קשר',
    video: {
      _section: 'סרטונים',
      trailers: 'טריילרים (מזהי YouTube)',
      clips: 'קטעים מההצגה',
      customerClips: 'עדויות לקוחות',
      clipItem: {
        youtubeId: 'מזהה YouTube',
        caption: 'כותרת',
      },
    },
    recommendationIds: 'המלצות מקושרות',
    clipIds: 'טעימות מההצגה (מהספרייה)',
    customerClipIds: 'אנשים מדברים (מהספרייה)',
    labels: {
      _section: 'טקסטים בעמוד ההצגה',
      _hint: 'השאירי ריק כדי להשתמש בטקסט ברירת המחדל. שימושי להתאמה בין הצגה לסדנא או לכל ניסוח אישי.',
      heroEyebrowFeatured: 'תווית עליונה — הצגה מומלצת',
      heroEyebrowDefault: 'תווית עליונה — הצגה רגילה',
      formatsLabel: 'תווית שתי גרסאות ההצגה',
      containedShowsTitle: 'כותרת רשימת ההצגות שבסדנא',
      aboutTitle: 'כותרת "על ההצגה / על הסדנא"',
      socialProofTitle: 'כותרת "ניסיון וקהלים"',
      clipsTitle: 'כותרת אזור הטעימות',
      galleryTitle: 'כותרת הגלריה',
      textTestimonialsTitle: 'כותרת ההמלצות הכתובות',
      videoTestimonialsTitle: 'כותרת ההמלצות בוידאו',
    },
  },

  clip: {
    _entity: 'טעימה',
    _entityPlural: 'טעימות מההצגות',
    id: 'מזהה (ID)',
    youtubeId: 'מזהה YouTube',
    caption: 'כותרת / תיאור',
    linkedTarget: 'שייך ל (לתיוג בלבד — לא משפיע על האתר)',
  },

  customerClip: {
    _entity: 'עדות לקוח',
    _entityPlural: 'אנשים מדברים על ההצגות',
    id: 'מזהה (ID)',
    youtubeId: 'מזהה YouTube',
    caption: 'כותרת / שם הממליץ',
    linkedTarget: 'שייך ל (לתיוג בלבד — לא משפיע על האתר)',
  },

  category: {
    _entity: 'קטגוריה',
    _entityPlural: 'קטגוריות',
    id: 'מזהה (ID)',
    slug: 'כתובת URL ידידותית (אופציונלי)',
    title: 'שם הקטגוריה',
    description: 'תיאור קצר',
    mainImg: 'תמונה ראשית',
    itemIds: 'הצגות וסדנאות בקטגוריה (סדר התצוגה)',
    trailers: 'טריילרים (מזהי YouTube)',
    clipIds: 'טעימות נוספות מהספרייה',
    customerClipIds: 'עדויות נוספות מהספרייה',
    recommendationIds: 'המלצות מקושרות',
    gallery: 'גלריית תמונות',
    extendedHtml: 'תוכן נוסף (HTML)',
    labels: {
      _section: 'טקסטים בעמוד הקטגוריה',
      _hint: 'השאירי ריק כדי להשתמש בטקסט ברירת המחדל.',
      eyebrow: 'תווית עליונה ("קטגוריה")',
      itemsTitle: 'כותרת רשימת ההצגות בקטגוריה',
      trailersTitle: 'כותרת הטריילרים',
      clipsTitle: 'כותרת הטעימות',
      galleryTitle: 'כותרת הגלריה',
      textTestimonialsTitle: 'כותרת ההמלצות הכתובות',
      videoTestimonialsTitle: 'כותרת ההמלצות בוידאו',
    },
  },

  homepage: {
    _entity: 'דף הבית',
    items: 'כרטיסיות בדף הבית (סדר התצוגה)',
    itemKind: 'סוג',
    itemKindOptions: {
      show: 'הצגה / סדנא',
      category: 'קטגוריה',
    },
    itemId: 'בחר/י פריט',
  },

  collection: {
    _entity: 'אוסף / כרטיס',
    _entityPlural: 'אוספים',
    id: 'מזהה (ID)',
    slug: 'כתובת URL ידידותית (אופציונלי)',
    type: 'סוג הכרטיס',
    typeOptions: {
      single: 'קישור להצגה יחידה',
      collection: 'אוסף של כמה הצגות',
    },
    title: 'כותרת',
    description: 'תיאור קצר',
    extendedHtml: 'תוכן מורחב (HTML)',
    mainImg: 'תמונה ראשית',
    priority: 'חשיבות תצוגה',
    linkedShowId: 'הצגה מקושרת',
    showIds: 'הצגות באוסף',
    gallery: 'גלריית תמונות',
    videos: 'סרטונים (מזהי YouTube)',
    recommendationIds: 'המלצות מקושרות',
  },

  recommendation: {
    _entity: 'המלצה',
    _entityPlural: 'המלצות',
    id: 'מזהה (ID)',
    recommenderName: 'שם הממליץ/ה',
    recommenderRole: 'תפקיד / מוסד',
    recommenderImage: 'תמונת הממליצ/ה (אופציונלי)',
    contactInfo: 'פרטי יצירת קשר',
    date: 'תאריך ההמלצה',
    content: 'תוכן ההמלצה (HTML)',
    linkedTarget: {
      _section: 'ההמלצה מתייחסת אל',
      kind: 'סוג',
      kindOptions: {
        show: 'הצגה',
        collection: 'אוסף',
      },
      id: 'בחר/י פריט',
      none: 'ללא קישור (המלצה כללית)',
    },
  },

  pageAbout: {
    _entity: 'עמוד "קצת עלי"',
    title: 'כותרת',
    mainImage: 'תמונה ראשית',
    mainDescription: 'תיאור ראשי',
    testimonials: 'ציטוטים מומלצים',
    testimonialItem: {
      author: 'שם הממליצ/ה',
      fromShowTitle: 'מאיזו הצגה',
      showId: 'הצגה מקושרת',
      recommendationId: 'המלצה מקושרת',
      text: 'טקסט הציטוט',
    },
  },

  pagePuppets: {
    _entity: 'עמוד "עולם הבובות"',
    title: 'כותרת',
    subtitle: 'כותרת משנה',
    paragraph: 'פסקת הסבר',
    youtubeVideoId: 'סרטון YouTube (מזהה)',
    infoSectionTitle: 'כותרת אזור העקרונות',
    infoListTitle: 'כותרת רשימת העקרונות',
    infoList: 'רשימת עקרונות',
    infoListItem: {
      title: 'כותרת עקרון',
      text: 'הסבר',
    },
    summaryQuote: 'ציטוט סיום',
  },

  homeGallery: {
    _entity: 'גלריה בעמוד הבית',
    images: 'תמונות הגלריה',
  },

  homeTestimonials: {
    _entity: 'המלצות בדף הבית',
    activeSectionTitle: 'ההמלצות בקרוסלה (לפי סדר התצוגה)',
    activeSectionHint: 'הכרטיס הראשון יוצג ראשון. החיצים ↑ ↓ מזיזים, × מסיר.',
    librarySectionTitle: 'כל ההמלצות בספרייה',
    librarySectionHint: 'כל ההמלצות שיש לך. ניתן להוסיף לקרוסלה או להעתיק את הטקסט המלא לשליחה ללקוח.',
    autoplaySeconds: 'החלפה אוטומטית (שניות, 0 = מבוטל)',
    unsavedHint: 'השינויים יישמרו רק לאחר לחיצה על ״שמירה״.',
    overrides: {
      _section: 'עקיפת תצוגה (אופציונלי)',
      hint: 'אם השדה ריק — נשתמש במידע המקורי מההמלצה.',
      quoteOverride: 'טקסט קצר לכרטיס',
      authorOverride: 'שם להצגה',
      fromShowTitleOverride: 'הצגה / הקשר',
    },
    actions: {
      editDisplay: 'עריכת תצוגה',
      closeEdit: 'סגירת עריכה',
      addToCarousel: 'הוסיפי לקרוסלה',
      alreadyInCarousel: 'בקרוסלה',
      copyFullText: 'העתק טקסט מלא',
    },
    toasts: {
      added: 'נוספה לקרוסלה — שמרי כדי לקבע',
      copied: 'הועתק ללוח',
      copyFailed: 'לא ניתן להעתיק אוטומטית — פתחי את דף ההמלצה והעתיקי ידנית',
      saved: 'נשמר',
      alreadyAdded: 'ההמלצה כבר נמצאת בקרוסלה',
    },
    emptyActive: 'אין כרגע המלצות בקרוסלה. הוסיפי מהספרייה למטה.',
    emptyLibrary: 'אין המלצות זמינות — צרי המלצות בכרטיסיית ״המלצות״ תחילה.',
    missingRecommendation: 'ההמלצה הזו לא נמצאת בספרייה — מומלץ להסיר',
    librarySearchPlaceholder: 'חיפוש לפי שם / תפקיד / תוכן...',
    libraryFilterAriaLabel: 'סינון לפי שיוך',
  },

  common: {
    categoryOptions: {
      kids: 'ילדים',
      youth: 'בני נוער',
      adults: 'מבוגרים',
    },
    priorityOptions: {
      featured: 'מומלץ (הבלטה)',
      normal: 'רגיל',
    },
    actions: {
      save: 'שמירה',
      cancel: 'ביטול',
      delete: 'מחיקה',
      add: 'הוספה',
      edit: 'עריכה',
      preview: 'תצוגה מקדימה',
      uploadImage: 'העלאת תמונה',
    },
    validation: {
      required: 'שדה חובה',
      invalidUrl: 'קישור לא תקין',
      invalidYoutubeId: 'מזהה YouTube לא תקין',
    },
  },
} as const;
